version: "3.8"

services:
  frontend:
    build: .
    command: "npm run dev -- --host"
    volumes:
      - static_volume:/home/app/microservice/static
    expose: 
      - "82"
    ports:
      - "82:82"
    restart: always

networks:
  generative-network:

volumes:
  static_volume:
 
