version: "3.8"

services:
  nginx:
    build: .
    ports:
      - "82:82"
    volumes:
      - static_volume:/home/app/microservice/static
    restart: always
    networks:
      - generative-network

networks:
  generative-network:

volumes:
  static_volume: